project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About"
        file: index.qmd
      - text: "CV"
        file: cv.qmd
      - section: "Football Projects"
        contents:
        - text: "Tracking Models (Viz)"
          file: visuals.qmd
        - text: "Data-driven contents"
          file: side_football.qmd
      - text: "Side Projects"
        file: side.qmd
      - text: "Contacts"
        file: contact.qmd

format:
  html:
    css: styles.css
    toc: true

execute:
  freeze: auto