---
title: "Curriculum Vitae"
subtitle: "Last updated: February, 2024"
toc: true
---

## Work experiences  {{< fa solid building >}}

#### Head of Data Science 

[**Math&Sport**](https://mathandsport.com/) / *Milan, Italy*\
**April 2022 - Present**

**ML on Football Tracking Data and Event Data for Lega Serie A** \
**Goal**: developing algorithms and KPIs for live, pre and post-match analysis on **Hawkeye** Skeleton data and **Opta** Event Data. \
Primarly for Lega Serie A clubs (supporting decision making process) and also Media Partner (*DAZN, Cronache di spogliatoio*).

#### Researcher Intern (Data Analyst)

[**Transcrime**](https://www.transcrime.it/en/) - [**Crime&Tech**](https://crimetech.it/) / *Milan, Italy*\
*January 2022 - March 2022*

**Applied research, ML and innovation to prevent and control crime for EU-funded research projects** \
**Goal**: developing Risk Indicators, Risk Assesment Models and Tools (interactive dashboards) to assess Corruption Risk factors in firms’ Ownership Structure. \


## Computer skills  {{< fa solid floppy-disk >}}

| Programming | Else |
|---|---|
| Data analysis and statistical modeling with **Python**, **R** (*scikit-learn, PyTorch*). | **Git**  /  **GitHub**  /  **GitLab** |
| Data wrangling and visualization in **Pyhton**, **R** (*Pandas, Polars, numpy, Matplotlib, mplsoccer*). | Interactive data apps with Python framework **Streamlit** and **Flet** (basics). |
| Knowledge in Cloud computing services on **AWS** (**S3**, **EC2**, **EKS**) | Back-end skills with **MongoDB**, **PostgreSQL**, **Python-Django** (basics). |
| Collaborative work with **Google Workspace**, **Slack**, **Trello**. | **OS**: Linux, Windows. |

&nbsp;

## Courses - Certifications  {{< fa solid spinner >}}

**AWS EC2 Basics** [*AWS Skill Builder*, October 2024]

**AWS EKS Primer** [*AWS Skill Builder*, October 2024]

**Amazon Elastic Kubernetes Service (Amazon EKS) - Troubleshooting** [*AWS Skill Builder*, October 2024]

[**Sport and Data Pioneer Award 2024**](https://forbes.it/2024/10/04/sport-innovation-l-evento-di-forbes-italia/) [*Forbes Italy for Math&Sport*, October 2024]

**Preliminary English Test - Council of Europe - Level B1** [*Cambridge Assessment English*, June 2012]

**English Language proficiency statement - Level B2** [*CLA Bologna*, June 2018]

**National Finals of Giochi Matematici** [*Università Bocconi - Milano*, Spring 2009]

&nbsp;

## Education  {{< fa solid school >}}

#### Mathematical Modelling of Football

**Uppsala Universitet** / *Uppsala, Sweden*\
*August 2021 - November 2021*

Course taught by Soccermatics author Prof. David Sumpter, with guest lectures. \
**Goal**: to show how to work with football data and understanding the game using coding, maths and stats. \

#### MSc Statistical Sciences (curriculum: Data Science)

**University of Bologna** / *Bologna, Italy*\
*September 2018 - Working opportunities*

#### Erasmus+ Study semester

**Aarhus Universitet** / *Aarhus, Denmark*\
*January 2020 - July 2020*

Gained experience with ML and programming, confronting a more hands-on learning approach. Improved (weekly) deadlines management, due to assignment-based assessment methods. \

#### BSc Mathematics

**University of Bologna** / *Bologna, Italy*\
*September 2014 - September 2018*

Graduated with 96 / 110 \
Dissertation (language: EN) in in High Frequency Finance: *VWAP OPTIMAL EXECUTION - Deterministic and stochastic approaches *"

&nbsp;

## Languages  {{< fa solid earth-europe >}}

Italian (mother tongue) - English (B2, advanced)

&nbsp;